//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMetrics.Logic.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppMetrics.Logic.Resources.Mails", typeof(Mails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics&lt;/title&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///  &lt;table align=&quot;center&quot; width=&quot;440&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; style=&quot;font-size:12px; color:#000; font-family:Arial, Helvetica, sans-serif&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;40&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;360&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;40&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;40&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;360&quot; style=&quot;color:#FFF; padding:6px 0;&quot;&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailAccountCreated {
            get {
                return ResourceManager.GetString("MailAccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics. Alerta vencida.&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin-top: 0; margin-left: 0; margin-right: 0; margin-bottom: 0;&quot;&gt;
        ///    &lt;table align=&quot;center&quot; width=&quot;100%&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;ffffff&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;table align=&quot;center&quot; width=&quot;640&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                        &lt;tbody&gt;
        ///                            &lt;tr&gt;
        ///                           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailAlertExpired {
            get {
                return ResourceManager.GetString("MailAlertExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics. Informe de viajes.&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin-top: 0; margin-left: 0; margin-right: 0; margin-bottom: 0;&quot;&gt;
        ///    &lt;table align=&quot;center&quot; width=&quot;100%&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;ffffff&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;table align=&quot;center&quot; width=&quot;640&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                        &lt;tbody&gt;
        ///                            &lt;tr&gt;
        ///                        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailFewTrips {
            get {
                return ResourceManager.GetString("MailFewTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics. Solicitud de viajes.&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin-top: 0; margin-left: 0; margin-right: 0; margin-bottom: 0;&quot;&gt;
        ///    &lt;table align=&quot;center&quot; width=&quot;100%&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;ffffff&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;table align=&quot;center&quot; width=&quot;640&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                        &lt;tbody&gt;
        ///                            &lt;tr&gt;
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailFewTripsToSeller {
            get {
                return ResourceManager.GetString("MailFewTripsToSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics. Recuperar contraseña&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin-top: 0; margin-left: 0; margin-right: 0; margin-bottom: 0;&quot;&gt;
        ///    &lt;table align=&quot;center&quot; width=&quot;100%&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;ffffff&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;table align=&quot;center&quot; width=&quot;640&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                        &lt;tbody&gt;
        ///                            &lt;tr&gt;
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailRecoverPassword {
            get {
                return ResourceManager.GetString("MailRecoverPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics. Solicitud de viajes.&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin-top: 0; margin-left: 0; margin-right: 0; margin-bottom: 0;&quot;&gt;
        ///    &lt;table align=&quot;center&quot; width=&quot;100%&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;ffffff&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;table align=&quot;center&quot; width=&quot;640&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                        &lt;tbody&gt;
        ///                            &lt;tr&gt;
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailReplyRequestTrips {
            get {
                return ResourceManager.GetString("MailReplyRequestTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;AppMetrics. Solicitud de viajes.&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body bgcolor=&quot;#ffffff&quot; style=&quot;margin-top: 0; margin-left: 0; margin-right: 0; margin-bottom: 0;&quot;&gt;
        ///    &lt;table align=&quot;center&quot; width=&quot;100%&quot; cellpadding=&quot;0&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; bgcolor=&quot;ffffff&quot;&gt;
        ///        &lt;tbody&gt;
        ///            &lt;tr&gt;
        ///                &lt;td&gt;
        ///                    &lt;table align=&quot;center&quot; width=&quot;640&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot;&gt;
        ///                        &lt;tbody&gt;
        ///                            &lt;tr&gt;
        ///                      [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailRequestTrips {
            get {
                return ResourceManager.GetString("MailRequestTrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  &lt;table width=&quot;440&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; style=&quot;font-size:12px; color:#000; font-family:Arial, Helvetica, sans-serif&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;40&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;360&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;40&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;40&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;360&quot; style=&quot;color:#FFF; pa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailUserRequest {
            get {
                return ResourceManager.GetString("MailUserRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///  &lt;table width=&quot;440&quot; border=&quot;0&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot; style=&quot;font-size:12px; color:#000; font-family:Arial, Helvetica, sans-serif&quot;&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;40&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;360&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;40&quot; bgcolor=&quot;#000000&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///    &lt;/tr&gt;
        ///    &lt;tr&gt;
        ///      &lt;td width=&quot;40&quot;&gt;&amp;nbsp;&lt;/td&gt;
        ///      &lt;td width=&quot;360&quot; style=&quot;color:#FFF; pa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MailUserWithOutLogin {
            get {
                return ResourceManager.GetString("MailUserWithOutLogin", resourceCulture);
            }
        }
    }
}
