//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMetrics.WCFAppMetrics.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2015 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.6.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Errors {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Errors object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Errors() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("AppMetrics.WCFAppMetrics.Resources.Errors", typeof(Errors).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al aceptar el viaje: {0}'.
        /// </summary>
        public static string AcceptTrip {
            get {
                return ResourceManager.GetString(ResourceNames.AcceptTrip, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al consultar las nuevas alertas: {0}'.
        /// </summary>
        public static string CheckNewAlerts {
            get {
                return ResourceManager.GetString(ResourceNames.CheckNewAlerts, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al chequear la version: {0}'.
        /// </summary>
        public static string CheckVersion {
            get {
                return ResourceManager.GetString(ResourceNames.CheckVersion, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al enviar mensaje al contacto de confianza: {0}'.
        /// </summary>
        public static string ContactMessage {
            get {
                return ResourceManager.GetString(ResourceNames.ContactMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al crear el viaje programado: {0}'.
        /// </summary>
        public static string CreateScheduleTrip {
            get {
                return ResourceManager.GetString(ResourceNames.CreateScheduleTrip, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al procesar las acciones programadas: {0}'.
        /// </summary>
        public static string DoActions {
            get {
                return ResourceManager.GetString(ResourceNames.DoActions, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al recuperar el texto About Us: {0}'.
        /// </summary>
        public static string GetAboutUs {
            get {
                return ResourceManager.GetString(ResourceNames.GetAboutUs, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener el listado de alertas: {0}'.
        /// </summary>
        public static string GetAllAlerts {
            get {
                return ResourceManager.GetString(ResourceNames.GetAllAlerts, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener las ciudades: {0}'.
        /// </summary>
        public static string GetCities {
            get {
                return ResourceManager.GetString(ResourceNames.GetCities, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener el cliente: {0}'.
        /// </summary>
        public static string GetClientUser {
            get {
                return ResourceManager.GetString(ResourceNames.GetClientUser, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener las empresas: {0}'.
        /// </summary>
        public static string GetCompanies {
            get {
                return ResourceManager.GetString(ResourceNames.GetCompanies, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener los mensajes del usuario: {0}'.
        /// </summary>
        public static string GetMessagesByUser {
            get {
                return ResourceManager.GetString(ResourceNames.GetMessagesByUser, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener el detalle de un alerta: {0}'.
        /// </summary>
        public static string GetMsgAlerts {
            get {
                return ResourceManager.GetString(ResourceNames.GetMsgAlerts, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener los taxis cercanos: {0}'.
        /// </summary>
        public static string GetNearTaxis {
            get {
                return ResourceManager.GetString(ResourceNames.GetNearTaxis, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener los mensajes del usuario: {0}'.
        /// </summary>
        public static string GetNewMessagesByUser {
            get {
                return ResourceManager.GetString(ResourceNames.GetNewMessagesByUser, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener el metodo de pago: {0}'.
        /// </summary>
        public static string GetPaymentMethod {
            get {
                return ResourceManager.GetString(ResourceNames.GetPaymentMethod, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener los grupos relacionados: {0}'.
        /// </summary>
        public static string GetRelatedGroups {
            get {
                return ResourceManager.GetString(ResourceNames.GetRelatedGroups, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener los usuarios relacionados: {0}'.
        /// </summary>
        public static string GetRelatedUsers {
            get {
                return ResourceManager.GetString(ResourceNames.GetRelatedUsers, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener la posicion del taxi en curso: {0}'.
        /// </summary>
        public static string GetTaxiPosition {
            get {
                return ResourceManager.GetString(ResourceNames.GetTaxiPosition, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener los datos del taxista asignado al trip: {0}'.
        /// </summary>
        public static string GetTaxiUserID {
            get {
                return ResourceManager.GetString(ResourceNames.GetTaxiUserID, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener el viaje: {0}'.
        /// </summary>
        public static string GetTrip {
            get {
                return ResourceManager.GetString(ResourceNames.GetTrip, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener la cantidad de mensajes no leidos: {0}'.
        /// </summary>
        public static string GetUnreadMessagesCount {
            get {
                return ResourceManager.GetString(ResourceNames.GetUnreadMessagesCount, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al obtener las zonas: {0}'.
        /// </summary>
        public static string GetZones {
            get {
                return ResourceManager.GetString(ResourceNames.GetZones, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error de autenticacion: {0}'.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString(ResourceNames.Login, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al cerrar sesion: {0}'.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString(ResourceNames.Logout, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al eliminar un archivo: {0}'.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString(ResourceNames.RemoveFile, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al eliminar el mensaje: {0}'.
        /// </summary>
        public static string RemoveMessage {
            get {
                return ResourceManager.GetString(ResourceNames.RemoveMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al enviar el mensaje: {0}'.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString(ResourceNames.SendMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al validar la sesion: {0}'.
        /// </summary>
        public static string SessionExpiredValidation {
            get {
                return ResourceManager.GetString(ResourceNames.SessionExpiredValidation, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al establecer el alerta como leida: {0}'.
        /// </summary>
        public static string SetAlertAsRead {
            get {
                return ResourceManager.GetString(ResourceNames.SetAlertAsRead, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al establecer la calificacion del viaje: {0}'.
        /// </summary>
        public static string SetCalificationTrip {
            get {
                return ResourceManager.GetString(ResourceNames.SetCalificationTrip, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al establecer el mensaje como leido: {0}'.
        /// </summary>
        public static string SetReadMessage {
            get {
                return ResourceManager.GetString(ResourceNames.SetReadMessage, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error la compartir el archivo: {0}'.
        /// </summary>
        public static string ShareUserFile {
            get {
                return ResourceManager.GetString(ResourceNames.ShareUserFile, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al cambiar el estado de trackeo: {0}'.
        /// </summary>
        public static string SwitchTrackingState {
            get {
                return ResourceManager.GetString(ResourceNames.SwitchTrackingState, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'Error al actualizar el viaje programado: {0}'.
        /// </summary>
        public static string UpdateScheduleTrip {
            get {
                return ResourceManager.GetString(ResourceNames.UpdateScheduleTrip, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al aceptar el viaje: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AcceptTripFormat(object arg0) {
            return string.Format(_resourceCulture, AcceptTrip, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al consultar las nuevas alertas: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CheckNewAlertsFormat(object arg0) {
            return string.Format(_resourceCulture, CheckNewAlerts, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al chequear la version: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CheckVersionFormat(object arg0) {
            return string.Format(_resourceCulture, CheckVersion, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al enviar mensaje al contacto de confianza: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ContactMessageFormat(object arg0) {
            return string.Format(_resourceCulture, ContactMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al crear el viaje programado: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string CreateScheduleTripFormat(object arg0) {
            return string.Format(_resourceCulture, CreateScheduleTrip, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al procesar las acciones programadas: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string DoActionsFormat(object arg0) {
            return string.Format(_resourceCulture, DoActions, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al recuperar el texto About Us: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetAboutUsFormat(object arg0) {
            return string.Format(_resourceCulture, GetAboutUs, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener el listado de alertas: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetAllAlertsFormat(object arg0) {
            return string.Format(_resourceCulture, GetAllAlerts, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener las ciudades: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetCitiesFormat(object arg0) {
            return string.Format(_resourceCulture, GetCities, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener el cliente: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetClientUserFormat(object arg0) {
            return string.Format(_resourceCulture, GetClientUser, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener las empresas: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetCompaniesFormat(object arg0) {
            return string.Format(_resourceCulture, GetCompanies, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener los mensajes del usuario: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetMessagesByUserFormat(object arg0) {
            return string.Format(_resourceCulture, GetMessagesByUser, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener el detalle de un alerta: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetMsgAlertsFormat(object arg0) {
            return string.Format(_resourceCulture, GetMsgAlerts, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener los taxis cercanos: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetNearTaxisFormat(object arg0) {
            return string.Format(_resourceCulture, GetNearTaxis, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener los mensajes del usuario: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetNewMessagesByUserFormat(object arg0) {
            return string.Format(_resourceCulture, GetNewMessagesByUser, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener el metodo de pago: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetPaymentMethodFormat(object arg0) {
            return string.Format(_resourceCulture, GetPaymentMethod, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener los grupos relacionados: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetRelatedGroupsFormat(object arg0) {
            return string.Format(_resourceCulture, GetRelatedGroups, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener los usuarios relacionados: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetRelatedUsersFormat(object arg0) {
            return string.Format(_resourceCulture, GetRelatedUsers, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener la posicion del taxi en curso: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetTaxiPositionFormat(object arg0) {
            return string.Format(_resourceCulture, GetTaxiPosition, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener los datos del taxista asignado al trip: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetTaxiUserIDFormat(object arg0) {
            return string.Format(_resourceCulture, GetTaxiUserID, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener el viaje: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetTripFormat(object arg0) {
            return string.Format(_resourceCulture, GetTrip, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener la cantidad de mensajes no leidos: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetUnreadMessagesCountFormat(object arg0) {
            return string.Format(_resourceCulture, GetUnreadMessagesCount, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al obtener las zonas: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string GetZonesFormat(object arg0) {
            return string.Format(_resourceCulture, GetZones, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error de autenticacion: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LoginFormat(object arg0) {
            return string.Format(_resourceCulture, Login, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al cerrar sesion: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string LogoutFormat(object arg0) {
            return string.Format(_resourceCulture, Logout, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al eliminar un archivo: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string RemoveFileFormat(object arg0) {
            return string.Format(_resourceCulture, RemoveFile, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al eliminar el mensaje: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string RemoveMessageFormat(object arg0) {
            return string.Format(_resourceCulture, RemoveMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al enviar el mensaje: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SendMessageFormat(object arg0) {
            return string.Format(_resourceCulture, SendMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al validar la sesion: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SessionExpiredValidationFormat(object arg0) {
            return string.Format(_resourceCulture, SessionExpiredValidation, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al establecer el alerta como leida: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SetAlertAsReadFormat(object arg0) {
            return string.Format(_resourceCulture, SetAlertAsRead, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al establecer la calificacion del viaje: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SetCalificationTripFormat(object arg0) {
            return string.Format(_resourceCulture, SetCalificationTrip, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al establecer el mensaje como leido: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SetReadMessageFormat(object arg0) {
            return string.Format(_resourceCulture, SetReadMessage, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error la compartir el archivo: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string ShareUserFileFormat(object arg0) {
            return string.Format(_resourceCulture, ShareUserFile, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al cambiar el estado de trackeo: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string SwitchTrackingStateFormat(object arg0) {
            return string.Format(_resourceCulture, SwitchTrackingState, arg0);
        }
        
        /// <summary>
        /// Formats a localized string similar to 'Error al actualizar el viaje programado: {0}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string UpdateScheduleTripFormat(object arg0) {
            return string.Format(_resourceCulture, UpdateScheduleTrip, arg0);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'AcceptTrip'.
            /// </summary>
            public const string AcceptTrip = "AcceptTrip";
            
            /// <summary>
            /// Stores the resource name 'CheckNewAlerts'.
            /// </summary>
            public const string CheckNewAlerts = "CheckNewAlerts";
            
            /// <summary>
            /// Stores the resource name 'CheckVersion'.
            /// </summary>
            public const string CheckVersion = "CheckVersion";
            
            /// <summary>
            /// Stores the resource name 'ContactMessage'.
            /// </summary>
            public const string ContactMessage = "ContactMessage";
            
            /// <summary>
            /// Stores the resource name 'CreateScheduleTrip'.
            /// </summary>
            public const string CreateScheduleTrip = "CreateScheduleTrip";
            
            /// <summary>
            /// Stores the resource name 'DoActions'.
            /// </summary>
            public const string DoActions = "DoActions";
            
            /// <summary>
            /// Stores the resource name 'GetAboutUs'.
            /// </summary>
            public const string GetAboutUs = "GetAboutUs";
            
            /// <summary>
            /// Stores the resource name 'GetAllAlerts'.
            /// </summary>
            public const string GetAllAlerts = "GetAllAlerts";
            
            /// <summary>
            /// Stores the resource name 'GetCities'.
            /// </summary>
            public const string GetCities = "GetCities";
            
            /// <summary>
            /// Stores the resource name 'GetClientUser'.
            /// </summary>
            public const string GetClientUser = "GetClientUser";
            
            /// <summary>
            /// Stores the resource name 'GetCompanies'.
            /// </summary>
            public const string GetCompanies = "GetCompanies";
            
            /// <summary>
            /// Stores the resource name 'GetMessagesByUser'.
            /// </summary>
            public const string GetMessagesByUser = "GetMessagesByUser";
            
            /// <summary>
            /// Stores the resource name 'GetMsgAlerts'.
            /// </summary>
            public const string GetMsgAlerts = "GetMsgAlerts";
            
            /// <summary>
            /// Stores the resource name 'GetNearTaxis'.
            /// </summary>
            public const string GetNearTaxis = "GetNearTaxis";
            
            /// <summary>
            /// Stores the resource name 'GetNewMessagesByUser'.
            /// </summary>
            public const string GetNewMessagesByUser = "GetNewMessagesByUser";
            
            /// <summary>
            /// Stores the resource name 'GetPaymentMethod'.
            /// </summary>
            public const string GetPaymentMethod = "GetPaymentMethod";
            
            /// <summary>
            /// Stores the resource name 'GetRelatedGroups'.
            /// </summary>
            public const string GetRelatedGroups = "GetRelatedGroups";
            
            /// <summary>
            /// Stores the resource name 'GetRelatedUsers'.
            /// </summary>
            public const string GetRelatedUsers = "GetRelatedUsers";
            
            /// <summary>
            /// Stores the resource name 'GetTaxiPosition'.
            /// </summary>
            public const string GetTaxiPosition = "GetTaxiPosition";
            
            /// <summary>
            /// Stores the resource name 'GetTaxiUserID'.
            /// </summary>
            public const string GetTaxiUserID = "GetTaxiUserID";
            
            /// <summary>
            /// Stores the resource name 'GetTrip'.
            /// </summary>
            public const string GetTrip = "GetTrip";
            
            /// <summary>
            /// Stores the resource name 'GetUnreadMessagesCount'.
            /// </summary>
            public const string GetUnreadMessagesCount = "GetUnreadMessagesCount";
            
            /// <summary>
            /// Stores the resource name 'GetZones'.
            /// </summary>
            public const string GetZones = "GetZones";
            
            /// <summary>
            /// Stores the resource name 'Login'.
            /// </summary>
            public const string Login = "Login";
            
            /// <summary>
            /// Stores the resource name 'Logout'.
            /// </summary>
            public const string Logout = "Logout";
            
            /// <summary>
            /// Stores the resource name 'RemoveFile'.
            /// </summary>
            public const string RemoveFile = "RemoveFile";
            
            /// <summary>
            /// Stores the resource name 'RemoveMessage'.
            /// </summary>
            public const string RemoveMessage = "RemoveMessage";
            
            /// <summary>
            /// Stores the resource name 'SendMessage'.
            /// </summary>
            public const string SendMessage = "SendMessage";
            
            /// <summary>
            /// Stores the resource name 'SessionExpiredValidation'.
            /// </summary>
            public const string SessionExpiredValidation = "SessionExpiredValidation";
            
            /// <summary>
            /// Stores the resource name 'SetAlertAsRead'.
            /// </summary>
            public const string SetAlertAsRead = "SetAlertAsRead";
            
            /// <summary>
            /// Stores the resource name 'SetCalificationTrip'.
            /// </summary>
            public const string SetCalificationTrip = "SetCalificationTrip";
            
            /// <summary>
            /// Stores the resource name 'SetReadMessage'.
            /// </summary>
            public const string SetReadMessage = "SetReadMessage";
            
            /// <summary>
            /// Stores the resource name 'ShareUserFile'.
            /// </summary>
            public const string ShareUserFile = "ShareUserFile";
            
            /// <summary>
            /// Stores the resource name 'SwitchTrackingState'.
            /// </summary>
            public const string SwitchTrackingState = "SwitchTrackingState";
            
            /// <summary>
            /// Stores the resource name 'UpdateScheduleTrip'.
            /// </summary>
            public const string UpdateScheduleTrip = "UpdateScheduleTrip";
        }
    }
}
