//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMetrics.WCFAppMetrics.Resources {
    using System;
    
    
    /// <summary>
    /// A strongly-typed resource class, for looking up localized strings, formatting them, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilderEx class via the ResXFileCodeGeneratorEx custom tool.
    // To add or remove a member, edit your .ResX file then rerun the ResXFileCodeGeneratorEx custom tool or rebuild your VS.NET project.
    // Copyright (c) Dmytro Kryvko 2006-2014 (http://dmytro.kryvko.googlepages.com/)
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("DMKSoftware.CodeGenerators.Tools.StronglyTypedResourceBuilderEx", "2.6.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
#if !SILVERLIGHT
    [global::System.Reflection.ObfuscationAttribute(Exclude=true, ApplyToMembers=true)]
#endif
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Naming", "CA1724:TypeNamesShouldNotMatchNamespaces")]
    public partial class Messages {
        
        private static global::System.Resources.ResourceManager _resourceManager;
        
        private static object _internalSyncObject;
        
        private static global::System.Globalization.CultureInfo _resourceCulture;
        
        /// <summary>
        /// Initializes a Messages object.
        /// </summary>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages() {
        }
        
        /// <summary>
        /// Thread safe lock object used by this class.
        /// </summary>
        public static object InternalSyncObject {
            get {
                if (object.ReferenceEquals(_internalSyncObject, null)) {
                    global::System.Threading.Interlocked.CompareExchange(ref _internalSyncObject, new object(), null);
                }
                return _internalSyncObject;
            }
        }
        
        /// <summary>
        /// Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(_resourceManager, null)) {
                    global::System.Threading.Monitor.Enter(InternalSyncObject);
                    try {
                        if (object.ReferenceEquals(_resourceManager, null)) {
                            global::System.Threading.Interlocked.Exchange(ref _resourceManager, new global::System.Resources.ResourceManager("AppMetrics.WCFAppMetrics.Resources.Messages", typeof(Messages).Assembly));
                        }
                    }
                    finally {
                        global::System.Threading.Monitor.Exit(InternalSyncObject);
                    }
                }
                return _resourceManager;
            }
        }
        
        /// <summary>
        /// Overrides the current thread's CurrentUICulture property for all
        /// resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return _resourceCulture;
            }
            set {
                _resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} de {1} {2}'.
        /// </summary>
        public static string AlertDate {
            get {
                return ResourceManager.GetString(ResourceNames.AlertDate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'La operación no es válida para este usuario'.
        /// </summary>
        public static string InvalidOperation {
            get {
                return ResourceManager.GetString(ResourceNames.InvalidOperation, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'El mensaje no existe'.
        /// </summary>
        public static string MessageNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.MessageNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to '{0} {1}/{2}/{3} | {4}:{5}'.
        /// </summary>
        public static string MessagesDate {
            get {
                return ResourceManager.GetString(ResourceNames.MessagesDate, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'El lugar seleccionado no existe'.
        /// </summary>
        public static string PlaceNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.PlaceNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Looks up a localized string similar to 'El usuario no es valido'.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString(ResourceNames.UserNotFound, _resourceCulture);
            }
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} de {1} {2}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        public static string AlertDateFormat(object arg0, object arg1, object arg2) {
            return string.Format(_resourceCulture, AlertDate, arg0, arg1, arg2);
        }
        
        /// <summary>
        /// Formats a localized string similar to '{0} {1}/{2}/{3} | {4}:{5}'.
        /// </summary>
        /// <param name="arg0">An object (0) to format.</param>
        /// <param name="arg1">An object (1) to format.</param>
        /// <param name="arg2">An object (2) to format.</param>
        /// <param name="arg3">An object (3) to format.</param>
        /// <param name="arg4">An object (4) to format.</param>
        /// <param name="arg5">An object (5) to format.</param>
        /// <returns>A copy of format string in which the format items have been replaced by the String equivalent of the corresponding instances of Object in arguments.</returns>
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1025:ReplaceRepetitiveArgumentsWithParamsArray")]
        public static string MessagesDateFormat(object arg0, object arg1, object arg2, object arg3, object arg4, object arg5) {
            return string.Format(_resourceCulture, MessagesDate, arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        /// <summary>
        /// Lists all the resource names as constant string fields.
        /// </summary>
        public class ResourceNames {
            
            /// <summary>
            /// Stores the resource name 'AlertDate'.
            /// </summary>
            public const string AlertDate = "AlertDate";
            
            /// <summary>
            /// Stores the resource name 'InvalidOperation'.
            /// </summary>
            public const string InvalidOperation = "InvalidOperation";
            
            /// <summary>
            /// Stores the resource name 'MessageNotFound'.
            /// </summary>
            public const string MessageNotFound = "MessageNotFound";
            
            /// <summary>
            /// Stores the resource name 'MessagesDate'.
            /// </summary>
            public const string MessagesDate = "MessagesDate";
            
            /// <summary>
            /// Stores the resource name 'PlaceNotFound'.
            /// </summary>
            public const string PlaceNotFound = "PlaceNotFound";
            
            /// <summary>
            /// Stores the resource name 'UserNotFound'.
            /// </summary>
            public const string UserNotFound = "UserNotFound";
        }
    }
}
